#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require 'report.php';
 
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
 
(new Application('Acme Cleaning', '1.0.0'))
      ->register('generate-report')

      ->addArgument('fileName',
          InputArgument::OPTIONAL,
          'Name of the file you wish to write to. Note: Please add the extension to the filename.')

      ->setCode(function (InputInterface $input, OutputInterface $output) {
        $reportClass = new Report();
        $file = $input->getArgument('fileName');

        $report = $reportClass->generateReportArray();
        $reportClass->writeToCsv($report, $file);

	    return $output->writeln("<info>Report generated! Thank you for using Acme Cleaning.</info>");

      })
      ->getApplication()
      ->run();	
